### PR TITLE
Portfolio: application deploy

### PR DESCRIPTION
**Pull request by Sboursen**
# Description

> For this milestone, I made my website available online through Github pages.
Please use this [link](https://sboursen.github.io/My-portfolio/) to visit the page.

- [x] Deploy your website using GitHub Pages.

- [x] Check the online version of your portfolio and make sure that the page works properly.

- [x] Update the README of your repository to include a link to the online version.

- [ ] **_No linter errors !!!!_**

> I am well aware that I have these linter errors in Style.css:
```
 174:3  ✖  Invalid value for `margin-left`       csstree/validator
 179:3  ✖  Invalid value for `margin-right`      csstree/validator
 316:3  ✖  Invalid value for `margin-left`       csstree/validator
 321:3  ✖  Invalid value for `margin-right`      csstree/validator
 340:3  ✖  Invalid value for `background-size`   csstree/validator
 348:3  ✖  Invalid value for `margin`            csstree/validator
```

> However, I would like to keep these changes because they help achieve better looks in my website by adding a variable `margin` to the grids. This was achieved using a combination of the `min()` and the `calc()` function which for some reason is not accepted by the linter.

> Example 

```
  margin-right:
    min(
      calc(0.19 * (100vw - 375px) + 24px),
      142px
    );
```
### **Please contact me if you need any further clarification regarding this issue.**

Best,

### CODE REVIEW

**Review by elmar8287 — CHANGES_REQUESTED** [review]
Hi @Sboursen ,

Great work on making the project requirements 👏 

- The Demo live link works 👍 
- The README file is updated with demo live link 👍 

There are still some requirements that aren't done yet, please work on it and ask for another review.
      
 ## Required Changes ♻️

- [x] Please, fix your linter error regarding `.css` file.  Sure you can use calc() anywhere where you would use numeric values (e.g.: width, max-height, margin-left, …), but max() and min() have been dropped from CSS3 Values and Units. That is why linter gives error. Please, try to replace them and I find another solution.  Reference [link](https://www.w3.org/Style/CSS/Tracker/issues/203)

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Sboursen** [comment]
Hi @elmar8287,
Thank you for the thorough review.
Is there any specific place where I can find details about the linter errors?
Or should I just google them?

**Comment by Sboursen** [comment]
I found a workaround.
I'm no longer using the unsupported `min()` function.

**Review by brytebee — APPROVED** [review]
Hi @Sboursen👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
> Hi @elmar8287, Thank you for the thorough review. Is there any specific place where I can find details about the linter errors? Or should I just google them?

Dear @Sboursen,

It is good that you found the way for a solution. I see your code. Nice job is done 👍

**Pull request merged**
